<?php
/**
 * Created by PhpStorm.
 * User: kevin
 * Date: 6/03/2018
 * Time: 9:07 PM
 */

namespace Kevupton\WordpressDatabaseMigrations;

class NewWpdb extends \wpdb
{
    public function query ($query)
    {
        return parent::query($query); // TODO: Change the autogenerated stub
    }
}